### ISSUE TITLE
OTA not kicking off?

### ISSUE THREAD

**Issue by Redferne** [theolind/pymysensors#118]
Excuse my lack of Python expertice, but I can't get the update_fw to kick in. I figured that the reboot of the node is never taking place. I tried with persistance also.

```
import logging
import mysensors.mysensors as mysensors

logging.basicConfig(level=logging.DEBUG)
_LOGGER = logging.getLogger(__name__)

def event(msg):
    """Callback for mysensors updates."""
    print("GW: " + str(msg.gateway) + "\tNode: " + str(msg.node_id) + "\tChild: " + str(msg.child_id) + "\tType: " + str(msg.type) + "\

GATEWAY = mysensors.SerialGateway(
  '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0', event_callback=event, persistence=False,
  protocol_version='2.0', baud=115200)

_LOGGER.debug("Starting FW Update")
GATEWAY.update_fw(2, 1, 1, fw_path='mysensors/carheater.hex')

_LOGGER.debug("Starting Gateway")

GATEWAY.start()
```

Output:
```
DEBUG:__main__:Starting Gateway
INFO:mysensors.gateway_serial:Trying to connect to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
INFO:mysensors.gateway_serial:/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 is open...
INFO:mysensors.gateway_serial:Connected to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
INFO:mysensors:n:0 c:255 t:3 s:14 p:Gateway startup complete.
GW: SerialGateway	Node: 0	Child: 255	Type: 0	Ack: 0	Sub: 18	Payload: 2.2.0-rc.2
WARNING:mysensors:Node 2 is unknown
INFO:mysensors:Requesting new presentation for node 2
GW: SerialGateway	Node: 2	Child: 255	Type: 0	Ack: 0	Sub: 18	Payload: 2.2.0-rc.2
GW: SerialGateway	Node: 2	Child: 255	Type: 3	Ack: 0	Sub: 11	Payload: Car Heater
GW: SerialGateway	Node: 2	Child: 255	Type: 3	Ack: 0	Sub: 12	Payload: 0.3
GW: SerialGateway	Node: 2	Child: 0	Type: 0	Ack: 0	Sub: 3	Payload: Heater
GW: SerialGateway	Node: 2	Child: 1	Type: 0	Ack: 0	Sub: 13	Payload: Consumption
GW: SerialGateway	Node: 2	Child: 2	Type: 0	Ack: 0	Sub: 6	Payload: Temperature
GW: SerialGateway	Node: 2	Child: 3	Type: 0	Ack: 0	Sub: 7	Payload: Humidity
GW: SerialGateway	Node: 2	Child: 4	Type: 0	Ack: 0	Sub: 22	Payload: CO
GW: SerialGateway	Node: 2	Child: 1	Type: 1	Ack: 0	Sub: 17	Payload: 5.82
GW: SerialGateway	Node: 2	Child: 2	Type: 1	Ack: 0	Sub: 0	Payload: 9.7
GW: SerialGateway	Node: 2	Child: 3	Type: 1	Ack: 0	Sub: 1	Payload: 37
GW: SerialGateway	Node: 2	Child: 4	Type: 1	Ack: 0	Sub: 37	Payload: 4
DEBUG:__main__:Starting FW Update
GW: SerialGateway	Node: 2	Child: 1	Type: 1	Ack: 0	Sub: 17	Payload: 6.16
GW: SerialGateway	Node: 2	Child: 2	Type: 1	Ack: 0	Sub: 0	Payload: 9.6
GW: SerialGateway	Node: 2	Child: 3	Type: 1	Ack: 0	Sub: 1	Payload: 37
GW: SerialGateway	Node: 2	Child: 4	Type: 1	Ack: 0	Sub: 37	Payload: 4
GW: SerialGateway	Node: 2	Child: 255	Type: 3	Ack: 0	Sub: 11	Payload: Car Heater
GW: SerialGateway	Node: 2	Child: 255	Type: 3	Ack: 0	Sub: 12	Payload: 0.3
WARNING:mysensors:child_id 0 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 1 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 2 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 3 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 4 already exists in children of node 2, cannot add child
GW: SerialGateway	Node: 2	Child: 0	Type: 1	Ack: 0	Sub: 2	Payload: 0
GW: SerialGateway	Node: 2	Child: 1	Type: 1	Ack: 0	Sub: 17	Payload: 6.54
GW: SerialGateway	Node: 2	Child: 2	Type: 1	Ack: 0	Sub: 0	Payload: 9.6
GW: SerialGateway	Node: 2	Child: 3	Type: 1	Ack: 0	Sub: 1	Payload: 37
GW: SerialGateway	Node: 2	Child: 4	Type: 1	Ack: 0	Sub: 37	Payload: 4

```

**Comment by MartinHjelmare** [comment]
Requesting a firmware update is only supported for already known sensors. So either you have to do it during gateway operation after the node has presented itself successfully, or have a valid persistence file with a presented node, and request the update after instantiating the gateway. The persistence file will be loaded during gateway instantiation in `__init__`.

**Comment by MartinHjelmare** [comment]
Btw, thanks for testing! :+1:

The readme probably needs to explain this feature a lot more.

**Comment by Redferne** [comment]
Tried that, same problem.

Python:
```
import time
import logging
import mysensors.mysensors as mysensors

logging.basicConfig(level=logging.DEBUG)
_LOGGER = logging.getLogger(__name__)

def event(msg):
    """Callback for mysensors updates."""
    print("GW: " + str(msg.gateway) + "\tNode: " + str(msg.node_id) + "\tChild: " + str(msg.child_id) + "\tType: " + str(msg.type) + "\tAck: " + str(msg.ack) + "\tSub: " + str(msg.sub_type) + "\tPayload: " + str(msg.payload))

GATEWAY = mysensors.SerialGateway(
  '/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0', event_callback=event, persistence=True,
  persistence_file='mysensors/mysensors_fw.json', protocol_version='2.0', baud=115200,
  timeout=1.0, reconnect_timeout=10.0)

_LOGGER.debug("Starting Gateway")
GATEWAY.start()

time.sleep(6)

_LOGGER.debug("Starting FW Update")
GATEWAY.update_fw(2, 1, 1, fw_path='mysensors/carheater.hex')

```
Output:

```
DEBUG:__main__:Starting Gateway
INFO:mysensors.gateway_serial:Trying to connect to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
INFO:mysensors.gateway_serial:/dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 is open...
INFO:mysensors.gateway_serial:Connected to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
DEBUG:__main__:Starting FW Update
GW: SerialGateway	Node: 2	Child: 1	Type: 1	Ack: 0	Sub: 17	Payload: 5.78
GW: SerialGateway	Node: 2	Child: 2	Type: 1	Ack: 0	Sub: 0	Payload: 6.6
GW: SerialGateway	Node: 2	Child: 3	Type: 1	Ack: 0	Sub: 1	Payload: 37
GW: SerialGateway	Node: 2	Child: 4	Type: 1	Ack: 0	Sub: 37	Payload: 3
GW: SerialGateway	Node: 2	Child: 255	Type: 3	Ack: 0	Sub: 11	Payload: Car Heater
GW: SerialGateway	Node: 2	Child: 255	Type: 3	Ack: 0	Sub: 12	Payload: 0.3
WARNING:mysensors:child_id 0 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 1 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 2 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 3 already exists in children of node 2, cannot add child
WARNING:mysensors:child_id 4 already exists in children of node 2, cannot add child
GW: SerialGateway	Node: 2	Child: 0	Type: 1	Ack: 0	Sub: 2	Payload: 0
```
Persistance file:
```
{
    "2": {
        "sensor_id": 2,
        "children": {
            "0": {
                "id": 0,
                "type": 3,
                "description": "Heater",
                "values": {
                    "2": "0"
                }
            },
            "1": {
                "id": 1,
                "type": 13,
                "description": "Consumption",
                "values": {
                    "17": "5.78"
                }
            },
            "2": {
                "id": 2,
                "type": 6,
                "description": "Temperature",
                "values": {
                    "0": "6.6"
                }
            },
            "3": {
                "id": 3,
                "type": 7,
                "description": "Humidity",
                "values": {
                    "1": "37"
                }
            },
            "4": {
                "id": 4,
                "type": 22,
                "description": "CO",
                "values": {
                    "37": "3"
                }
            }
        },
        "type": 18,
        "sketch_name": "Car Heater",
        "sketch_version": "0.3",
        "battery_level": 0,
        "protocol_version": "2.2.0-rc.2"
    }
}

```

**Comment by MartinHjelmare** [comment]
It's weird that your node sends sketch info  which is usually done during presentation, after sending set messages of type 1. The gateway also logs as if it just received presentation messages of those sensors, since it says they already exist.

Id like to see your sketch.

**Comment by Redferne** [comment]
Well. There's nothing special to the node code AFAIK. It is however far away and out in the freezing cold. It there something I can do to force sending new firmware to it? I have an urgent update I need to push. Thanks.

**Comment by MartinHjelmare** [comment]
You need it to reboot for it to request a firmware config. You can check the `reboot` attribute of the sensor in the `sensors` dictionary on the gateway instance. Set reboot to `True`. The node ID also needs to be in `gateway.ota.requested` dictionary.

**Comment by Redferne** [comment]
Sorry for being daft, but can you please provide a code example? I quickly glanced over the code and I could see that the upgrade_fw should take care of rebooting the node and such?

**Comment by MartinHjelmare** [comment]
Yeah, `upgrade_fw' should take care of everything. If you want to dig deeper when troubleshooting, the attributes I mentioned above are relevant in this case.
You can access them like this:
```py
GATEWAY.sensors[2].reboot
GATEWAY.ota.requested
```

**Comment by dirkclemens** [comment]
I really would like to use this approach with python instead of a Windows Application (Mac/linux User), but I am lost. Whats the flow in the ota process?

1. GATEWAY = mysensors.SerialGateway()
2. GATEWAY.start()
3. GATEWAY.sensors[nodeid] = Sensor(nodeid)
4. GATEWAY.update_fw(nodeid, 1, 1, fw_path='whatever.hex')
5. print (GATEWAY.ota.requested) 

or 1, 2, 4, 3, 5, or what else?

To what point in time do I call 
GATEWAY.sensors[nodeid].reboot

or is that done automatically within update_fw() which is calling make_update() that again is doing a reboot at the end. I understood that one has to perform a reboot to *start* the ota process. 

is version 2.2.0-rc.2 of MySensors already supported by pymysensors?

Thanks in advance :-)

**Comment by MartinHjelmare** [comment]
You have to do 1. and 2. Note that you need to pass the correct arguments when instantiating the `SerialGateway`.

Step 3. is handled automatically by the gateway instance, when devices send the needed presentation messages.

Step 4. you need to call to load the hex firmware file and set the `reboot` attribute to `True`, which will send a reboot request message to the node when the node sends its next set message. So you don't need to change the `reboot` attribute manually.

The above conversation was meant in a troubleshooting context. So if everything works, only step 4 is needed after the gateway instance is set up and all devices presented properly.

**Comment by dirkclemens** [comment]
Thanks, @MartinHjelmare ,  got it 👍 
The "type" and "version" seemed to be critical, you have to take care for that. Seems that type, version and firmware are begin checked, and I always used the same wrong combination when testing.

So the process is really quite simple:
step 1: GATEWAY = mysensors.TCPGateway(...) # I use TCP instead of Serial ..
step 2: GATEWAY.start()	
step 3: GATEWAY.update_fw(1, 1, 1, fw_path='whatever.hex')

**Comment by MartinHjelmare** [comment]
:+1: That's how it should work. Note that sending firmware puts a lot of strain on your radio network between the gateway and node in question. So a network that had no issues sending short infrequent messages, can turn up having problems coping with a firmware upgrade. It also requires a gateway that can handle sending messages at a high rate. So power capacity and power stability for the gateway is important.

**Comment by Redferne** [comment]
Excuse my utter lameness :banana: I made the ignorant mistake of trying to upgrade a node which did not feature the OTA bootloader :tongue: The firmware update works perfectly! Thank you for this feature.

**Comment by Redferne** [comment]
I posted this in the HomeAssistant forum as well. But maybe it is better suited here:

> The update procedure does not trigger immediately, but waits for a SET request from the node before sending the reboot command. I would really like to have the possibility to force an update by shooting the reboot command when the service is called. Could be added as a “force” parameter to the service call? Like urgently pushing new firmware to nodes.
> 
> In non-forced “normal” mode maybe it’s good to wait for any life sign from the node, not only SET requests. I have a few battery powered nodes that sometimes only sends heartbeat every now and then. They might have to wait for a very long time before receiving new firmware. Since they maybe only sends SET requests once a day.
> 

Thoughts?

**Comment by MartinHjelmare** [comment]
The reason why it's waiting for a set message before sending the reboot request, is exactly to cater for battery driven devices. They will only be able to receive the reboot request just after coming a live when sending a message.

It could still be useful to add a force option, to quicker update non battery driven devices.
