### ISSUE TITLE
Callback when a node is added?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#197]
Is there a way to get a callback when a new node is discovered and given an ID? This would make it easier to start the process of presenting the new node to the controller (in this case the Mozilla Gateway)

**Comment by flatsiedatsie** [comment]
I discovered I could check if the message type is "3", which must be the presentation type. That already helps a lot.

**Comment by MartinHjelmare** [comment]
Presentation messages have message type 0. When a presentation message comes in the registered event callback will be called with the message instance.

**Comment by flatsiedatsie** [comment]
You're right, the presentation messages can be analyzed.

I'm still figuring out the best way to know when a node has been completely mapped. For now I just set a 30 second delay before iterating over the node dictionary.

**Comment by MartinHjelmare** [comment]
Maybe don't assume that the node is ever done? Just parse the incoming messages via event callback and update as needed?

**Comment by flatsiedatsie** [comment]
I wasn't sure the Mozilla Gateway supported that. But it does. I rewrote the entire adapter today. It works much better now. The Asyncio is also great at speeding things up. Really nice job!
