### ISSUE TITLE
Getting some strange concatenation of node ID's?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#199]
I have a MySensors node which sends data to the Serial gateway that is connected to my Raspberry Pi.

It has node ID 3.

Most of the time this ID comes through ok. But ever so often I get a strange effect that the ID is 'stretched out':

`Not a valid message: Not valid node_id: 333333 for dictionary value @ data['node_id']`

Most often the 3 will transform into 33. Sometimes it gets longer, like the example above.

// edit: bingo:

`Node 33 is unknown`

**Comment by flatsiedatsie** [comment]
One more example:

`
message> id: 4-255; payload: Carbon sensor

child_id 2 already exists in children of node 4, cannot add child
message> id: 4-255; payload: 1.3

Not a valid message: Not valid node_id: 4444 for dictionary value @ data['node_id']
message> id: 4-2; payload: -1

Node 44 is unknown
Node 44 is unknown
`

**Comment by MartinHjelmare** [comment]
We need more info. Please capture parallell serial logs from the node, and set log level to debug to see the what is received from the gateway serial connection.

**Comment by flatsiedatsie** [comment]
I haven't come across the issue anymore. It must have been an issue on my end, probably with the transmittion power/stability.

**Comment by MartinHjelmare** [comment]
Thanks for getting back with a possible explanation. :+1:
