### ISSUE TITLE
Child values have random keys?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#200]
When reading the values from a child, the 'values' attribute has unpredictable keys. For example:

`<ChildSensor child_id=2, child_type=22, description=Carbon dioxide, values: {43: 'ppm', 37: '847'}>`

Why are they 43 and 37, and not 0 and 1?

**Comment by flatsiedatsie** [comment]
Another example: 
`<ChildSensor child_id=2, child_type=8, description=Barometer (HPa), values: {4: '1031.0', 5: 'Stable'}>`

**Comment by MartinHjelmare** [comment]
We're following the mysensors serial api:
https://www.mysensors.org/download/serial_api_20

**Comment by flatsiedatsie** [comment]
Yes, it makes total sense. I just didn't understand.
