### ISSUE TITLE
Anticipate messages from presentation only?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#202]
I have a node that presents two S_INFO children.
```
  present(PHONENUMBER1_ID, S_INFO,F("Phone number 1")); wait(RF_DELAY);
  present(PHONENUMBER2_ID, S_INFO,F("Phone number 1")); wait(RF_DELAY);
```
In PyMySensors this presentation is reflected in the node dictionary as follows:

`<ChildSensor child_id=4, child_type=36, description=Password 1, values: {}>`

If a subtype is presented but not populated yet, would it be an idea to do this?

`<ChildSensor child_id=4, child_type=36, description=Password 1, values: {'47':''}>`

It would make it a lot easier to pre-populate properties in controllers even when no actual data has been sent yet. For example, my node receives SMS, and only sends the data along when that SMS is received, which is a rare occurrence. Yet I'd like my interface to already show that the child exists and is a text property.

**Comment by MartinHjelmare** [comment]
How would we know what value types to pre-populate the child with?

**Comment by flatsiedatsie** [comment]
I was actually wrong (again :-) ) The issue is slightly different than I initially thought.

The presentation message does indeed not contain the V_type.

My issue, it turns out, is simply that empty messages are not treated as messages.

For example, here is the raw serial message from Minicom. It starts with the presentation messages. But it's the ending where the issue is:

```
2;3;0;0;36;Password 1
2;4;0;0;36;Password 1
2;5;0;0;19;Lock 1
2;6;0;0;19;Lock 2
2;7;0;0;19;hello-goodbye button
2;8;0;0;36;Change to send SMS
2;10;0;0;36;Phone number 1
2;5;2;0;36;
2;6;2;0;36;
4;2;1;0;37;184
4;2;1;0;37;185
2;1;1;0;47;received phone 1
2;1;1;0;47;received phone 2
2;6;1;0;36;0
2;1;1;0;47;Button 1 pressed
2;3;2;0;47;
2;4;2;0;47;
```

The first empty items are:
```
2;5;2;0;36;
2;6;2;0;36;
```
These are two 'lock' types that send an empty 'V_LOCK_STATUS' (36) message. Because they are 'empty' they do not show up in the dictionary.

The same happens with the S_INFO children. Here you see two empty 'V_TEXT' (47) messages that do not show up in the value dictionary, probably because they are empty:

```
2;3;2;0;47;
2;4;2;0;47;
```
The change I would propose is to treat these messages as valid messages, and use them to populate the values dictionary.

Once all nodes have filled values dictionaries it is much easier to loop over all the found devices. An example of how I'm trying to do that can be found here:
https://github.com/createcandle/Webthings-mysensors-adapter/blob/master/pkg/mysensors_device.py#L62

**Comment by MartinHjelmare** [comment]
`2;5;2;0;36;` is a req command type message, not a set command type message. It's requesting a value for subtype 36 from the controller.

**Comment by flatsiedatsie** [comment]
Ah I see. Thanks.

So I guess there simply isn't data to start from, which explains the empty value dict completely.

Do you perhaps have a recommendation on how to deal with this?

Since S_INFO can only have V_TEXT, I have manually creates the property. I guess I could do that for all children with an empty values dict: try to anticipate which it will be if there is only one possibility.

**Comment by MartinHjelmare** [comment]
If it's possible to register a device property after initialization, I would use the event callback to do that when we have a value type for the child.
