### ISSUE TITLE
re-request presentation?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#205]
I'd like to ask all devices in the network to present themselves again.

I know this code does that, but I looked all over and couldn't find it. I also tried looking at creating a custom manual message, but didn't figure out how to do that.

Do you have a suggestion on how I can do this?

**Comment by MartinHjelmare** [comment]
Sending `I_DISCOVER_REQUEST` will ask all listening nodes (non sleeping) to send a `I_DISCOVER_RESPONSE`. In pymysensors we send this when the gateway replies with `I_GATEWAY_READY`.

When we get a `I_DISCOVER_RESPONSE` from a node, we check if the node is presented. If not we ask it to present again. This is already handled in pymysensors. Whenever we hear from a node or child that isn't properly presented we will ask for another presentation.

The only thing you might want to do manually is to send the `I_DISCOVER_REQUEST`.

**Comment by flatsiedatsie** [comment]
Thanks!

Could you elaborate a little on how I could make that call?

And how would I generate the message object? Can I just do something like:

`newMessage = Messsage()`

and then while going over the sensors object:

`newMessage.decode(sensor_id,255,3,0,19)`

Then I thought perhaps something like `GATEWAY.send(newMessage)`
I don't believe I can use GATEWAY.send() ?

**Comment by MartinHjelmare** [comment]
Use `copy` or `modify` methods on a `Message` instance. You can see them in use above.

You should be able to use `GATEWAY.send` method. Did you try it?

**Comment by flatsiedatsie** [comment]
Now that I've enabled persistence to avoid the duplicate-ID issue, I noticed that there is no longer a discovery request on startup. 

So I am once again hoping to create that request manually. Could you possibly help me with a code example?

**Comment by flatsiedatsie** [comment]
From the code above it would seem that a 'gateway ready' message should already always be followed up by a request to all nodes to present themselves?

Is it possible this is different for the asyncio version? Or if persistence is enabled?

**Comment by flatsiedatsie** [comment]
Perhaps even this might work?
`self.GATEWAY.send('0;255;3;0;26;0\n')`

**Comment by MartinHjelmare** [comment]
Activating persistence shouldn't affect whether or not a discovery request is sent.

The discovery request should be sent on gateway startup by pymysensors when we receive the gateway ready message and on a regular interval by the gateway mysensors library code itself.

**Comment by flatsiedatsie** [comment]
Interesting. So perhaps the issue is that the gateway doesn't stop when the adapter is restarted.

Is this the correct way to shut down the asyncio adapter?
```
    def unload(self):
        print("Shutting down adapter")
        try:
            self.GATEWAY.stop()
            self.LOOP.close()
        except:
            print("unable to cleanly close the PyMySensors gateway")
```

**Comment by flatsiedatsie** [comment]
I did used to see this error:
https://github.com/createcandle/Webthings-mysensors-adapter/issues/2

**Comment by MartinHjelmare** [comment]
You need to await `gateway.stop()`, since it's a coroutin, if it's the async gateway.
