### ISSUE TITLE
Unable to send message to actuator without delay between each char, Arduino Pro Mini 3.3 V

### ISSUE THREAD

**Issue by maxdrift** [theolind/pymysensors#21]
Hi! Thanks for the nice library I'm using through Home Assistant!!
I have my Serial Gateway (Arduino Pro Mini 3.3V) connected via Serial to USB converter to a i386 Linux embedded running Home Assistant.
By adding a relay actuator I was able to receive status messages, but unable to send ON/OFF commands.
After some tries using a serial console I've found out that in order to successfully send a command to the sensor I need to send the message with a small (1-3ms) delay between each char.
So I've modified [THIS](https://github.com/theolind/pymysensors/blob/master/mysensors/mysensors.py#L340) method from:
```python
    def send(self, message):
        """ Writes a Message to the gateway. """
        self.serial.write(message.encode())
```
to:
```python
    def send(self, message):
        """ Writes a Message to the gateway. """
        for m in message:
            self.serial.write(m.encode())
            time.sleep(0.001)
```
and now sending commands works.
Do you have any thoughts about this? Are you able to reproduce this behaviour?

**Comment by MartinHjelmare** [comment]
I've only been using Arduino Nano for gateways so far, and there you don't need to send one character at a time. I'll try to reproduce this with a pro mini and serial-ttl-usb.

**Comment by maxdrift** [comment]
Thanks!

**Comment by MartinHjelmare** [comment]
Hi!

I haven't had time to setup a test for this yet, but I think I have a clue to the problem. Have you tried setting the baudrate to something lower like 38400? At 8 MHz the Arduino will have trouble communicating at 115200 bps with a computer. Could you test this, using the vanilla send method?

```
gw = mysensors.SerialGateway('/dev/ttyACM0', event, baud=38400)
```

**Comment by maxdrift** [comment]
Yeah! Nice spot! I've tried using a baud rate of 57600 and 38400 and it works!
So it would be great to expose one more (optional) setting in the Home Assistant MySensors config to set the baud rate. What do you think?

Thanks!!

**Comment by MartinHjelmare** [comment]
Great! Yes, definitely.
