### ISSUE TITLE
Cannot handle numbers in description?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#210]
I had this presentation:

`present(D_CHILD_ID, S_HEATER, F("I * 10")); wait(RADIO_DELAY); `
`send(thermostatMsg.setSensor(I_CHILD_ID).set(I_value,2));  wait(RADIO_DELAY);`

..which seemed to have lead to a strange value in the node object:

`11: <ChildSensor child_id=11, child_type=4, description=I * 10, values: {3: '10', 45: '0.00'}>`

A similar child with normal name did not have that double value. For example:

`2: <ChildSensor child_id=2, child_type=14, description=Setpoint, values: {45: '66.00'}>`

Changing the name to just `I` solved the problem.

**Comment by MartinHjelmare** [comment]
It's hard to speculate with only this info. We need to see the serial log from the nodes to tell what's going on.

**Comment by flatsiedatsie** [comment]
Does this help?

```
DEBUG:mysensors:Receiving 11;10;0;0;14;P * 10
WARNING:mysensors.sensor:child_id 10 already exists in children of node 11, cannot add child
DEBUG:mysensors:Receiving 11;11;0;0;14;I * 10
WARNING:mysensors.sensor:child_id 11 already exists in children of node 11, cannot add child
...
DEBUG:mysensors:Receiving 11;10;1;0;45;1.00
>> message > set > id: 11; child: 10; subtype: 45; payload: 1.00
+ DEVICE.ADD_CHILD with child_id: 10
targetPropertyID = 11-10-45
<pkg.mysensors_property.MySensorsProperty object at 0x75d5d710>
new property in properties dict inside device: <pkg.mysensors_property.MySensorsProperty object at 0x75d5d710>
AddonManagerProxy: handle_device_added: MySensors_11
DEBUG:mysensors:Receiving 11;11;1;0;45;0.00
>> message > set > id: 11; child: 11; subtype: 45; payload: 0.00
+ DEVICE.ADD_CHILD with child_id: 11
targetPropertyID = 11-11-45
<pkg.mysensors_property.MySensorsProperty object at 0x74bc2c70>
new property in properties dict inside device: <pkg.mysensors_property.MySensorsProperty object at 0x74bc2c70>
AddonManagerProxy: handle_device_added: MySensors_11
DEBUG:mysensors:Receiving 11;12;1;0;45;0.00
>> message > set > id: 11; child: 12; subtype: 45; payload: 0.00
+ DEVICE.ADD_CHILD with child_id: 12
targetPropertyID = 11-12-45

```

**Comment by MartinHjelmare** [comment]
I don't see anything strange in that log.

**Comment by flatsiedatsie** [comment]
I wonder if `11;10;0;0;14;P * 10` could give a problem?

**Comment by MartinHjelmare** [comment]
The warnings for incorrect message are not triggered. You can add some debug prints eg inside the gateway `logic` method.
