### ISSUE TITLE
Is this a valid MQTT setup?

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#216]
I'm trying to add MQTT support to a plugin. Is this a valid way of doing it?

```
                    self.GATEWAY = mysensors.AsyncMQTTGateway(self.MQTTC.publish, self.MQTTC.subscribe, in_prefix='mygateway1-out',
                        out_prefix='mygateway1-in', retain=True, event_callback=self.mysensors_message,
                        persistence=True, persistence_file=self.persistence_file_path, 
                        protocol_version='2.2')
```

Context: https://forum.mysensors.org/topic/10539/mqtt-support

**Comment by MartinHjelmare** [comment]
Looks ok. Is it working?

**Comment by flatsiedatsie** [comment]
Not sure what you mean with the event loop argument, but this is how it's implemented now:
https://github.com/createcandle/Webthings-mysensors-adapter/blob/master/pkg/mysensors_adapter.py#L196

A user on the MySensors forum will test it soon.

I was a little confused that the OUT prefix is IN?
`out_prefix='mygateway1-in'`

But I'm assuming that's just an MQTT convention I don't understand.

**Comment by MartinHjelmare** [comment]
All the async gateways except an optional event `loop` parameter. If it's not passed the gateway will use the current running event loop via `asyncio.get_event_loop`.

The out prefix is for the outgoing messages, ie from pymysensors gateway to the broker. The in prefix is for incoming messages. To connect to the default mysensors mqtt gateway topics, we need to cross streams and connect the out prefix parameter to mygateway1-in and vice versa.

**Comment by flatsiedatsie** [comment]
Ah, so then I would have my own 'private' event loop that wouldn't have to be shared? Does that improve the speed/robustness?

**Comment by MartinHjelmare** [comment]
Usually you want a single event loop for the whole app. The point of asyncio is that it allows to write (cooperative) concurrent code in a single thread. There might be cases where the app needs more than one event loop, but I don't know good examples of that.
