### ISSUE TITLE
Sometimes error handling "Gateway startup complete." message

### ISSUE THREAD

**Issue by flatsiedatsie** [theolind/pymysensors#221]
I keep having a weird error that seems to come from decoding the gateway's startup message:

```
Error decoding message from gateway, bad data received: plete.
Not a valid message: not enough values to unpack (expected 5, got 0)

>> incoming message > presentation > id: 0; child: 255; subtype: 18; payload: 2.3.1

Error decoding message from gateway, bad data received: 33;2550;255;3;0;14;Gateway startup complete.
```

The `plete` seems to come from the last few characters of the "Gateway startup complete" message.

`Gateway startup complete.` is exactly 25 characters, which is the maximum payload size. So it should be ok.

It doesn't really matter - the gateway works fine anyway. But it's odd. Maybe it's a cut-off of the serial buffer?

**Comment by MartinHjelmare** [comment]
Ok. Yeah, I'm not sure what we could do here to solve that. Sounds more like a problem with the mysensors transport, where incomplete messages are received. Maybe check that all sides have good power sources. The radios are sensitive for lack of clean power.

**Comment by flatsiedatsie** [comment]
Well, it's only the very first message that has this. And it has this consistently. So I suspect it's a serial buffer issue.
