### ISSUE TITLE
Solution requested for integrating Mysensors with other system

### ISSUE THREAD

**Issue by chamroeunbm** [theolind/pymysensors#326]
Hello,
Currently, I am using Hardware Controller System for Hydroponics running on RPI. I want to add support for many wireless sensors(up to 50) and I want to use MySensors + its gateway but I don't want to use another controller.

My immediate solution is asking my current System to contact with MySensor Gateway thru Py MySensorGateway( https://github.com/theolind/pymysensors) without installing MySensor supported Controller.

Thanks;

**Comment by MartinHjelmare** [comment]
Hi! Sorry, I don't understand the question. What is your request?

**Comment by chamroeunbm** [comment]
Can Mysensors work without Controller(just sensor node and gateway)? I have my own existing system and I want to use Mysensors node to send data to Mysensors Gateway and my system will talk with the gateway thru this pymysensors as I don't want to have another Controller for Mysensors

**Comment by MartinHjelmare** [comment]
You can write Python code that uses pymysensors and talk to the gateway and its network, yes.

**Comment by chamroeunbm** [comment]
There's no needs to use Controller for mySensors node to work? I read Mysensors document, it said that the sensor node will request id and other config from Controller.

**Comment by MartinHjelmare** [comment]
The Python code you write together with pymysensors will be the controller. It will handle this. You can test this with the CLI in pymysensors. Install pymysensors and then run:
```
pymysensors --help
```

**Comment by chamroeunbm** [comment]
thanks, so my code will act as the controller? If so, what is the minimum requirement to do this? I don't find any simple example for implementing Controller for MySensors

**Comment by MartinHjelmare** [comment]
That depends on what you want to be able to do. Pymysensors tries to support the MySensors specification as far as possible. The rest is up to you.
