### ISSUE TITLE
Setting node state on message send causes issues in case of message drop

### ISSUE THREAD

**Issue by gorbunovav** [theolind/pymysensors#362]
Hi!

I am experiencing some issues with Home Assistant integration which uses this library.

It seems that the library stores the state of the node internally. 
And this state is set not only on message receive from the node, but on the command send to the node.

It also looks like the state is checked before sending new commands.

For me it causes issues with the `S_COVER` device class in case the `V_UP` or `V_DOWN` command never reaches the node.
There is no state report from the node itself in this case.

So Home Assistant thinks that the cover is e.g. `DOWN` and allows you to ask it to go up again, library thinks that it is `OPENING` and ignores subsequent `UP` commands, which renders the node unresponsive.

Detailed description of the case: home-assistant/core#51265.

Proposals:
- can the message delivery status be checked before setting the internal state?
- set state on message receive from the node only (or make it switchable - Home Assistant integration has the flag `optimistic` for this).
- is it really necessary to block commands based on the local state value?

**Comment by gorbunovav** [comment]
>can the message delivery status be checked before setting the internal state?

According to docs there is no concept of reporting the delivery status through the Serial API, so it is impossible without the API amendment:
https://www.mysensors.org/download/serial_api_20

In this case the only way to know that the command was received is to get response from the node, so the internal state should not be changed until that. On the node side the message send status is available to the user code and it is possible to implement some re-send logic.

>is it really necessary to block commands based on the local state value?

I think it is also better to be handled on the node side - at least node knows its own state better and developer can adjust behavior according to node specifics.

**Comment by MartinHjelmare** [comment]
Yes, I think the right approach is to not update the internal state until we receive a message with new state from the node.

**Comment by gorbunovav** [comment]
@MartinHjelmare I will try to fix this

**Comment by gorbunovav** [comment]
@MartinHjelmare Hi! What do we need to release these changes?

**Comment by MartinHjelmare** [comment]
I think we can release it. I can probably do it tomorrow.

**Comment by gorbunovav** [comment]
@MartinHjelmare thank you!

**Comment by MartinHjelmare** [comment]
0.22.0 is released. :+1: 

https://pypi.org/project/pymysensors/0.22.0/

**Comment by gorbunovav** [comment]
@MartinHjelmare great! 
It should "just work" with the current home assistant code (I am using the updated library version in my installation), so we just need to update the lib in home assistant to fix home-assistant/core#51265.

**Comment by MartinHjelmare** [comment]
Do you want to make a PR to Home Assistant?

**Comment by gorbunovav** [comment]
@MartinHjelmare I think I can use  home-assistant/core#47530 as a base - right?

**Comment by MartinHjelmare** [comment]
Yeah, update the manifest.json and then run the requirements script to update the requirements files, as mentioned in the PR template.
