### ISSUE TITLE
Install error on Home Assistant.

### ISSUE THREAD

**Issue by den2k** [theolind/pymysensors#5]
ERROR:mysensors.mysensors:Error decoding message from gateway
Traceback (most recent call last):
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 219, in run
    msg = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 1: invalid start byte

Any ideas?

**Comment by theolind** [comment]
MySensors will still work (just tested), this is just a problem when initially opening the serial device. However, this may be a bit confusing so I'll leave the issue open and see if I can do something about this in the future. Maybe treat this more as a warning and not as an error.

Anyway, thanks for reporting the issue!

**Comment by den2k** [comment]
I bring this up because I don't see the mysensor anywhere in the interface. I've setup configuration.yaml to include mysensors which is triggering the Error to show.

I have mysensors 1.5. installed on a Pro Mini Serial Gateway attached through a USB port (/dev/ttyUSB0) to my Pi 2.

I heard from the HA community that it only works with 1.4. Not sure if this is the case. 

Thanks.

**Comment by den2k** [comment]
Now further along.  Ran into some additional errors while in bootup, but looks like the serial gateway it was able to sync with the sensor node finally.

ERROR:mysensors.mysensors:Error decoding message from gateway
Traceback (most recent call last):
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 220, in run
    response = self.logic(msg)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 98, in logic
    msg = Message(data)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 279, in __init__
    self.decode(data)
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 299, in decode
    self.sub_type) = [int(f) for f in data]
  File "/home/pi/.homeassistant/lib/mysensors/mysensors.py", line 299, in <listcomp>
    self.sub_type) = [int(f) for f in data]
ValueError: invalid literal for int() with base 10: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
INFO:homeassistant.components.sensor.mysensors:sensor_update sensor_update: node 1
....

Is there some additional info on how to read sensor node data and display this data to the home assistant dashboard?  Some easy way to use the configuration.yaml file to do this. Thanks. PM me if easier.

**Comment by theolind** [comment]
I have been looking into this issue a bit more now. It does not seem to be a problem with the pymysensors library. During startup it happens from time to time that the gateway sends bad data to pymysensors, which gives the error. These situations can be ignored safely.

From what I can tell, if these errors occur multiple times after startup, the problem may be that code was compiled/uploaded using the wrong target board (For example mistaking Arduino Nano with ATmega 168 for Arduino Nano with ATmega 328).

The other question is probably better asked in the [home-assistant google group](https://groups.google.com/forum/#!forum/home-assistant-dev) or [home-assistant gitter chat](https://gitter.im/balloob/home-assistant). If you have enabled the mysensors component for home-assistant the measurements should appear on the dashboard. 

Closing this issue now.
