### ISSUE TITLE
Sensors loaded through persistence does not trigger subscription

### ISSUE THREAD

**Issue by clempat** [theolind/pymysensors#70]
# Step to reproduce (using H.A. for exemple)
- Activate persistence
- Let some sensors getting presented and report few data
- Restart H.A.

# Expected
- We subscribe back (C_SET, C_REQ) to those sensors

# What happen
- We never subscribe back and only subscribed to C_PRESENTATION, C_INTERNAL expect for those sensors as they already known and wont be added

**Comment by MartinHjelmare** [comment]
Thanks for the report!

**Comment by MartinHjelmare** [comment]
Fixed via https://github.com/theolind/pymysensors/pull/72.
