### ISSUE TITLE
Question: Information in event callback

### ISSUE THREAD

**Issue by steve-bate** [theolind/pymysensors#76]
Thanks for this library. It's been very useful for me. I'm curious why the event_callback only contains an update_type (always "sensor_update"?) and the node ID. Is there a technical reason why you don't callback with a more specific event type and the child sensor id? If not, I may add that information and submit a PR. Thanks again.

**Comment by MartinHjelmare** [comment]
Hi! No I don't think there's a technical reason for this. Only one I can think of is simplicity. PR for review is welcome. As changing the signature of the callback would probably be a breaking change for users of the library, the benefit of the change should be clearly motivated.

**Comment by MartinHjelmare** [comment]
Closed in https://github.com/theolind/pymysensors/pull/78.
