### ISSUE TITLE
Use of OTA with MYSBootloader

### ISSUE THREAD

**Issue by joliva** [theolind/pymysensors#82]
Will this also work with MYSBootloader?

**Comment by MartinHjelmare** [comment]
It should since MYSBootloader uses the same mysensors API for OTA, as far as I know. But I haven't had time to test that yet. If you do, please update this thread, and we can update the readme.

**Comment by joliva** [comment]
Thanks for the quick reply. I will give it a try over the next couple of days and let you know how it works out.

**Comment by joliva** [comment]
Sorry for the late reply.  It does work with MYSBootloader, but I had to make a change to get it to work.  It may very well be a misunderstanding on my part.

In mysensors/mysensors.py in Gateway:__init__()  I needed to move the initialization of self.ota from before  self._safe_load_sensors() to after it.

Thanks for sharing the project!

**Comment by MartinHjelmare** [comment]
Thanks for reporting back!

No you are correct and you've found a bug. Thanks for that as well. :smile:
I'll make a fix asap, and also update the readme about supporting MYSBootloader.
