### ISSUE TITLE
Publish pymysensors on pypi

### ISSUE THREAD

**Issue by andrey-git** [theolind/pymysensors#94]
Could you publish this package on Pypi, so it can be fetched without specifying the github URL?

home-assistant/home-assistant#7069

**Comment by MartinHjelmare** [comment]
@theolind what do you say? Would you be ok with and do you have time to register pymysensors on pypi and adding me as a maintainer?

**Comment by theolind** [comment]
I think this is a good idea. Will take care of it tonight.

**Comment by theolind** [comment]
Published on pypi: https://pypi.python.org/pypi/pymysensors
MartinHjelmare added as maintainer
